# Generated by Django 2.0.3 on 2018-04-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasUsers',
            fields=[
                ('account', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('uiduser', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='MobileUsers',
            fields=[
                ('login', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(default='', max_length=15)),
                ('password', models.CharField(max_length=36)),
                ('uiduser', models.CharField(max_length=36)),
                ('email', models.CharField(max_length=50)),
                ('mobilePhone', models.CharField(max_length=36)),
                ('inform', models.IntegerField()),
                ('datetimecreate', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('access_token', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('token_type', models.CharField(default='bearer', max_length=100)),
                ('expires_in', models.IntegerField(default=3600)),
                ('datetimecreate', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('uiduser', models.CharField(max_length=36)),
            ],
            options={
                'ordering': ['-datetimecreate'],
            },
        ),
    ]
