# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('news', models.TextField()),
                ('auth', models.BooleanField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='tarifs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff', models.CharField(max_length=50)),
                ('dateStart', models.DateTimeField()),
                ('dateEnd', models.DateTimeField()),
            ],
            options={
                'ordering': ['-dateStart'],
            },
        ),
        migrations.CreateModel(
            name='Uchastok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
