# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_auto_20180408_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasusers',
            name='uiduser',
            field=models.CharField(default='', max_length=36),
        ),
    ]
