# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_auto_20180409_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasusers',
            name='uiduser',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
